In [1]:
import numpy as np

In [148]:
# 7 x 5 
A = np.random.rand(7,5)
# 14 X 10
B = np.random.rand(14,10)
# 5 x 7
C = np.random.rand(5,7)

# Valid matrix multiplications
# A X C (14X10 * 10 X  14)
# C X B (10X14 * 14X10)

np.shape(C@A)
print(C)
print(A)

[[0.30504093 0.85712739 0.09490182 0.91110465 0.66220851 0.17029391
  0.75292377]
 [0.18982168 0.73550449 0.95098005 0.84878786 0.57025445 0.45575777
  0.35639668]
 [0.51023344 0.34939659 0.58776729 0.46708546 0.90912456 0.67952954
  0.74510971]
 [0.58069523 0.51660264 0.03024644 0.28477653 0.75437852 0.67766309
  0.32272608]
 [0.61428879 0.53881668 0.81948876 0.1877591  0.43310694 0.745301
  0.92850224]]
[[0.06975408 0.69552703 0.45298802 0.62474658 0.29701709]
 [0.4185765  0.01477947 0.92437171 0.33591382 0.21176717]
 [0.30454049 0.44551793 0.04452921 0.10678759 0.93644583]
 [0.05523745 0.91394645 0.14936729 0.22377225 0.21697765]
 [0.04163635 0.1774293  0.41043621 0.33052875 0.90079486]
 [0.02712029 0.9898674  0.58154626 0.09321764 0.05187854]
 [0.55565023 0.6881184  0.4862012  0.79172149 0.46208624]]


In [149]:
def matrix_mult(A,B):
    
    # get the matrix sizes
    szA = np.shape(A)
    szB = np.shape(B)

    # check sizes and give error if multiplication is not valid
    if szA[1] != szB[0]:
        raise ValueError('"Inner" dimensions don\'t match')
            
    # Initialize
    C = np.zeros((szA[1], szB[0]))
    # loop over the rows 
    for i in range(szA[0]):
        for j in range(szB[1]):
            C[i,j] = np.dot(A[i,:], B[:,j])
                
    return C

In [153]:

D = matrix_mult(C,A)
D

array([[0.90983241, 1.90397771, 1.80769991, 1.52336776, 1.5119379 ,
        0.        , 0.        ],
       [0.89173803, 2.13988451, 1.60737181, 1.17028167, 1.9888576 ,
        0.        , 0.        ],
       [0.85694166, 2.39547018, 1.7806308 , 1.55717607, 2.07579077,
        0.        , 0.        ],
       [0.51079599, 1.71198938, 1.6450905 , 1.17129947, 1.23581392,
        0.        , 0.        ],
       [1.08249225, 2.42543108, 1.90349729, 1.64204196, 1.96255805,
        0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        ]])

In [151]:
C@A

array([[0.90983241, 1.90397771, 1.80769991, 1.52336776, 1.5119379 ],
       [0.89173803, 2.13988451, 1.60737181, 1.17028167, 1.9888576 ],
       [0.85694166, 2.39547018, 1.7806308 , 1.55717607, 2.07579077],
       [0.51079599, 1.71198938, 1.6450905 , 1.17129947, 1.23581392],
       [1.08249225, 2.42543108, 1.90349729, 1.64204196, 1.96255805]])